version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"  # Port for gRPC      
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0    
    environment:
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      ENABLE_MODULES: text2vec-transformers  # Enable the transformers module
    depends_on:
      - t2v-transformers

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    ports:
      - "8081:8080"
    environment:
      ENABLE_CUDA: 0  # Set to 1 to enable GPU support

volumes:
  weaviate_data: